# Generated by Django 3.2.8 on 2021-11-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211103_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
