# Generated by Django 3.2.8 on 2021-11-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_coffees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_coffee', to='menu.menu')),
                ('cold_drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_drink', to='menu.menu')),
                ('hot_coffees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_coffee', to='menu.menu')),
                ('hot_drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_drink', to='menu.menu')),
                ('hot_teas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_tea', to='menu.menu')),
                ('iced_teas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_tea', to='menu.menu')),
            ],
        ),
    ]
