# Generated by Django 3.2.8 on 2021-11-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20211106_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drinks',
        ),
    ]
