# Generated by Django 3.2.8 on 2021-11-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_drinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
