# Generated by Django 3.2.8 on 2021-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_delete_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
