# Generated by Django 3.2.8 on 2021-11-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_categories_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='at_home_coffee',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='categories',
            name='drinks',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='categories',
            name='food',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='categories',
            name='merchandise',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='drinks',
            name='cold_coffees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_coffee', to='menu.categories'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='cold_drinks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_drink', to='menu.categories'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='hot_coffees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_coffee', to='menu.categories'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='hot_drinks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_drink', to='menu.categories'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='hot_teas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_tea', to='menu.categories'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='iced_teas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_tea', to='menu.categories'),
        ),
    ]
