# Generated by Django 3.2.8 on 2021-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20211106_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drinks',
        ),
    ]
