# Generated by Django 3.2.8 on 2021-11-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20211106_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='code',
        ),
    ]
